version: '2'

services:

  orderer.centralized-vehicle.com:
    container_name: orderer.centralized-vehicle.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enable TLS
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      #- GODEBUG=netdns=go
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/centralized-vehicle.com/orderers/orderer.centralized-vehicle.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/centralized-vehicle.com/orderers/orderer.centralized-vehicle.com/tls/:/var/hyperledger/orderer/tls
    - orderer.centralized-vehicle.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.rto.centralized-vehicle.com:
    container_name: peer0.rto.centralized-vehicle.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.rto.centralized-vehicle.com
      - CORE_PEER_ADDRESS=peer0.rto.centralized-vehicle.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.rto.centralized-vehicle.com:7053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7053
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.rto.centralized-vehicle.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.rto.centralized-vehicle.com:7051
      - CORE_PEER_LOCALMSPID=rtoNode
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/rto.centralized-vehicle.com/peers/peer0.rto.centralized-vehicle.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/rto.centralized-vehicle.com/peers/peer0.rto.centralized-vehicle.com/tls:/etc/hyperledger/fabric/tls
        - peer0.rto.centralized-vehicle.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.rto.centralized-vehicle.com:
    container_name: peer1.rto.centralized-vehicle.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.rto.centralized-vehicle.com
      - CORE_PEER_ADDRESS=peer1.rto.centralized-vehicle.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.rto.centralized-vehicle.com:8053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.rto.centralized-vehicle.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.rto.centralized-vehicle.com:7051
      - CORE_PEER_LOCALMSPID=rtoNode
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/rto.centralized-vehicle.com/peers/peer1.rto.centralized-vehicle.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/rto.centralized-vehicle.com/peers/peer1.rto.centralized-vehicle.com/tls:/etc/hyperledger/fabric/tls
        - peer1.rto.centralized-vehicle.com:/var/hyperledger/production

    ports:
      - 8051:8051
      - 8053:8053

  peer0.public.centralized-vehicle.com:
    container_name: peer0.public.centralized-vehicle.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.public.centralized-vehicle.com
      - CORE_PEER_ADDRESS=peer0.public.centralized-vehicle.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.public.centralized-vehicle.com:9053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.public.centralized-vehicle.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.public.centralized-vehicle.com:10051
      - CORE_PEER_LOCALMSPID=publicNode
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/public.centralized-vehicle.com/peers/peer0.public.centralized-vehicle.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/public.centralized-vehicle.com/peers/peer0.public.centralized-vehicle.com/tls:/etc/hyperledger/fabric/tls
        - peer0.public.centralized-vehicle.com:/var/hyperledger/production
    ports:
      - 9051:9051
      - 9053:9053

  peer1.public.centralized-vehicle.com:
    container_name: peer1.public.centralized-vehicle.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.public.centralized-vehicle.com
      - CORE_PEER_ADDRESS=peer1.public.centralized-vehicle.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer0.public.centralized-vehicle.com:10053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.public.centralized-vehicle.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.public.centralized-vehicle.com:9051
      - CORE_PEER_LOCALMSPID=publicNode
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/public.centralized-vehicle.com/peers/peer1.public.centralized-vehicle.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/public.centralized-vehicle.com/peers/peer1.public.centralized-vehicle.com/tls:/etc/hyperledger/fabric/tls
        - peer1.public.centralized-vehicle.com:/var/hyperledger/production
    ports:
      - 10051:10051
      - 10053:10053

  peer2.public.centralized-vehicle.com:
    container_name: peer2.public.centralized-vehicle.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2.public.centralized-vehicle.com
      - CORE_PEER_ADDRESS=peer2.public.centralized-vehicle.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.public.centralized-vehicle.com:11053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.public.centralized-vehicle.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.public.centralized-vehicle.com:9051
      - CORE_PEER_LOCALMSPID=publicNode
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/public.centralized-vehicle.com/peers/peer2.public.centralized-vehicle.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/public.centralized-vehicle.com/peers/peer2.public.centralized-vehicle.com/tls:/etc/hyperledger/fabric/tls
        - peer2.public.centralized-vehicle.com:/var/hyperledger/production
    ports:
      - 11051:11051
      - 11053:11053

  
